# Generated by Django 5.2 on 2025-04-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objet", "0002_objet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objet",
            name="status",
            field=models.CharField(
                choices=[
                    ("Actif", "Actif"),
                    ("Inactif", "Inactif"),
                    ("Maintenance", "Maintenance"),
                    ("Hors-Service", "Hors-Service"),
                    ("Occupé", "Occupé"),
                ],
                default="Inactif",
                max_length=20,
            ),
        ),
    ]
